"""
Django settings for OPKCWeb project.

Generated by 'django-admin startproject' using Django 5.2.6.
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# =========================================================
#  ENVIRONMENT CONFIGURATION (Local vs. Production)
# =========================================================

# We check if the specific server directory exists to determine where we are.
# If '/srv/openpkcommons' exists, we assume we are on the University Server.
IS_PRODUCTION = os.path.exists('/srv/openpkcommons')

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-j8yh&jwk85ynn+(*8k*@jrj+unt4nf-on3ytfg+85z6xp^$4=$'

if IS_PRODUCTION:
    print("--- ENVIRONMENT: PRODUCTION DETECTED ---")
    # SECURITY WARNING: don't run with debug turned on in production!
    DEBUG = False
    
    # Allow the University URL and the Domain Name
    ALLOWED_HOSTS = ['openpkcommons.org', 'www.openpkcommons.org']
    
    # Server-specific paths for static files
    STATIC_ROOT = '/srv/openpkcommons/static'
    MEDIA_ROOT = '/srv/openpkcommons/media'
    
else:
    print("--- ENVIRONMENT: LOCAL DEVELOPMENT DETECTED ---")
    # Local development settings
    DEBUG = True
    
    # Allow localhost for development
    ALLOWED_HOSTS = ['127.0.0.1', 'localhost']
    
    # Local paths (inside your project folder)
    STATIC_ROOT = BASE_DIR / 'staticfiles'
    MEDIA_ROOT = BASE_DIR / 'media'

# =========================================================


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'visualization',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'OPKCWeb.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'OPKCWeb.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
# Note: STATIC_ROOT is handled in the Logic Block at the top

MEDIA_URL = '/media/'
# Note: MEDIA_ROOT is handled in the Logic Block at the top

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'